### ISSUE TITLE
Install in Windows

### ISSUE THREAD

**Issue by Imsaiki** [KoichiYasuoka/spaCy-ixaKat#1]
Hello,

is spaCy-ixaKat only for 64-bit Linux?

Is it possible to install it on Windows?

Thank you.

Here is the error:

**Comment by KoichiYasuoka** [comment]
I tried to install spaCy-ixaKat on Windows or Cygwin, but sorry I could not. Furthurmore, [ixaKat](http://ixa2.si.ehu.eus/ixakat/ixa-pipe-dep-eu.php) still uses very old Java1.8...
